version: "3.5"
services:
        nginx:
                image: nginx:latest
                container_name: riverstream-nginx
                networks:
                        - riverstream-network
                ports:
                        - "127.0.0.1:8000:443"
                volumes:
                        - ../app:/var/www/html
                        - ./config/nginx.conf:/etc/nginx/nginx.conf
                        - ./config/default.conf:/etc/nginx/conf.d/default.conf
                        - ./config/server.crt:/etc/ssl/server.crt
                        - ./config/server.key:/etc/ssl/server.key
                restart: "on-failure"
                depends_on:
                        - php
                        - mysql
        php:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: riverstream-php
                container_name: riverstream-php
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                networks:
                        - riverstream-network
                volumes:
                        - ../app:/var/www/html
                        - ./config/php.ini:/usr/local/etc/php/php.ini
                        - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
                restart: "on-failure"

        mysql:
                image: mariadb:latest
                container_name: riverstream-mariadb
                networks:
                        - riverstream-network
                volumes:
                        - ./db:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
                        MYSQL_DATABASE: riverstream
                        MYSQL_USER: riverstream
                        MYSQL_PASSWORD: ${MYSQL_RIVERSTREAM_PASS}

                restart: "on-failure"
        node:
                image: node:latest
                container_name: riverstream-node
                networks:
                        - riverstream-network
                volumes:
                        - ../app:/home/node/app
                stdin_open: true
                tty: true
                restart: "on-failure"
networks:
        riverstream-network:
                name: riverstream-network
